name = "vue-worker-spa"
main = "index.js"
compatibility_date = "2024-01-01"

# Vue 构建产物目录
site = { bucket = "front/dist" }

[build]
# Cloudflare 会在部署前执行这个命令
# 假设你的前端在 "front" 文件夹
command = "cd front && pnpm install && pnpm run build"
[dev]
local_protocol = "http"
port = 8787